export const USERS_SET_FIRST_NAME = 'USERS_SET_FIRST_NAME';
export const USERS_SET_LAST_NAME = 'USERS_SET_LAST_NAME';
export const USERS_SET_PROPERTIES = 'USERS_INCREMENT_NAVIGATION_CLICKS';
export const USERS_INCREMENT_NAVIGATION_CLICKS = 'USERS_INCREMENT_NAVIGATION_CLICKS';

